version: 2
jobs:
  build:
    working_directory: ~/code/AndroidDemo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout: 
          path: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Check the project dir
          command: echo $PWD
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies          
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account  espresso-1@appspot.gserviceaccount.com --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Check apk
          command: |
              ls $PWD/app/build/outputs/apk/debug/app-debug.apk  $PWD/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          
      - run:
          name: Test with Firebase Test Lab
          command:  >
            sudo gcloud firebase test android run --type instrumentation \
              --app $PWD/app/build/outputs/apk/debug/app-debug.apk \
              --test $PWD/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}\
              --device model=Nexus5X,\
              version=26,\
              locale=en_US,\
              orientation=portrait 
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://[BUCKET_NAME]/[OBJECT_NAME] | tail -1` ${CIRCLE_ARTIFACTS}/ | true
