version: 2
jobs:
  build:
    working_directory: ~/code/AndroidDemo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout: 
          path: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Check the project dir
          command: echo $PWD
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies          
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            gcloud auth activate-service-account  --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            
      - run:
          name: Install Crmod dependency
          command: sudo pip install -U crcmod
          
      - run:
          name: Test with Firebase Test Lab
          command:  >
            gcloud firebase test android run --type instrumentation \
              --app $PWD/app/build/outputs/apk/debug/app-debug.apk \
              --test $PWD/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=Nexus5X,version=26,locale=en_US,orientation=portrait \
              --environment-variables coverage=true,coverageFile=/sdcard/tmp/code-coverage/connected/coverage.ec \
              --directories-to-pull=/sdcard/tmp --timeout 20m

      - run:
          name: Create directory to store test results
          command: mkdir firebase
          
      - run:
          name: Download testdata from Test-Lab
          command: 
            gsutil -m cp -r -U "`gsutil ls gs://$FIREBASE_TEST_LAB | tail -1`*"  firebase ||true
             
      - store_artifacts:
          path: /home/circleci/code/AndroidDemo/firebase
          destination: /firebase/

      - store_test_results:
          path: firebase
